import anthropic
from dotenv import load_dotenv

load_dotenv()
client = anthropic.Anthropic()

# 1. Define the tool schema
weather_tool_schema = {
    "name": "get_weather",
    "description": "Get current weather for a location",
    "input_schema": {
        "type": "object",
        "properties": {
            "location": {"type": "string"}
        },
        "required": ["location"]
    }
}

# Initial user query
messages = [
    {"role": "user", "content": "What is the weather like in Chicago?"}
]

try:
    # 2. First call to Claude
    response = client.messages.create(
        model="claude-sonnet-5",
        max_tokens=1024,
        tools=[weather_tool_schema],
        messages=messages
    )

    # Check if Claude initiated a tool call
    if response.stop_reason == "tool_use":
        # Append Claude's assistant turn to history
        messages.append({"role": "assistant", "content": response.content})

        tool_results = []
        for block in response.content:
            if block.type == "tool_use":
                # Capture the real dynamic ID generated by Claude
                real_tool_use_id = block.id

                # Simulate a 503 downstream service failure
                tool_results.append({
                    "type": "tool_result",
                    "tool_use_id": real_tool_use_id,
                    "is_error": True,  # Signals failure to Claude
                    "content": "Error 503: The downstream weather API is temporarily unavailable."
                })

        # Append the user turn containing the error tool_result
        messages.append({"role": "user", "content": tool_results})

        # 3. Call Claude again with the error feedback
        final_response = client.messages.create(
            model="claude-sonnet-5",
            max_tokens=1024,
            tools=[weather_tool_schema],
            messages=messages
        )

        # Print Claude's natural language handling of the error
        for block in final_response.content:
            if block.type == "text":
                print("\n--- Claude Response to Tool Error ---")
                print(block.text)

except Exception as e:
    print(f"Execution Error: {e}")