import json
import anthropic
from dotenv import load_dotenv
from rich import print as rprint

# Automatically reads .env and sets ANTHROPIC_API_KEY
load_dotenv()

# Initialize the client (picks up ANTHROPIC_API_KEY from environment)
client = anthropic.Anthropic()

# 1. Define the tool schema
weather_tool_schema = {
    "name": "get_weather",
    "description": "Get the current weather for a given location",
    "input_schema": {
        "type": "object",
        "properties": {
            "location": {
                "type": "string",
                "description": "The city and state, e.g. San Francisco, CA"
            },
            "unit": {
                "type": "string",
                "enum": ["celsius", "fahrenheit"],
                "description": "The temperature unit to use"
            }
        },
        "required": ["location"]
    }
}

# 2. Local tool execution logic
def get_weather(location, unit="fahrenheit"):
    return {
        "location": location,
        "temperature": "72",
        "unit": unit,
        "condition": "Sunny"
    }

# 3. Initial message history
messages = [
    {"role": "user", "content": "What is the weather like in Frederick, MD?"}
]

try:
    # 4. First API call offering the tool
    response = client.messages.create(
        # model="claude-3-5-sonnet-latest",
        model="claude-sonnet-5",
        max_tokens=1024,
        tools=[weather_tool_schema],
        messages=messages
    )

    print("\n--- Pretty Printed API Response ---")
    # print(json.dumps(response.model_dump(), indent=2))
    # rprint(response.model_dump())
    rprint(response.content)



    # 5. Check if Claude requested tool execution
    if response.stop_reason == "tool_use":
        # Append Claude's assistant message (contains tool_use block)
        messages.append({"role": "assistant", "content": response.content})

        tool_results = []
        for block in response.content:
            if block.type == "tool_use":
                if block.name == "get_weather":
                    # Run local code using arguments generated by Claude
                    output = get_weather(**block.input)

                    # Format tool result block
                    tool_results.append({
                        "type": "tool_result",
                        "tool_use_id": block.id,
                        "content": json.dumps(output)
                    })

        # Append execution outcome inside a user turn
        messages.append({"role": "user", "content": tool_results})

        # 6. Send results back to Claude for final response
        final_response = client.messages.create(
            # model="claude-3-5-sonnet-20241022",
            model="claude-sonnet-5",
            max_tokens=1024,
            tools=[weather_tool_schema],
            messages=messages
        )

        print("\n--- Final Answer ---")
        print(final_response.content[0].text)

except Exception as e:
    print(f"Execution Error: {e}")